### ISSUE TITLE
No IUserTokenProvider is registered.

### ISSUE THREAD

**Issue by JayVDZ** [JamesRandall/AccidentalFish.AspNet.Identity.Azure#10]
I can't be certain this issue is to do with the provider so please accept my apologies if it's just me being a dumbass... I'm getting the following exception:

`System.NotSupportedException: No IUserTokenProvider is registered.`

When I implement email confirmation during user registration:
`var token = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);`

If it's not me being a dumbass, could this be an unsupported feature of the new stuff mentioned in this issue?: 
https://github.com/JamesRandall/AccidentalFish.AspNet.Identity.Azure/issues/9

**Comment by alexmarshall132** [comment]
@Amethi Thank you so much for posting here. It really helped me troubleshoot my code and saved me time.

**Comment by samarmir** [comment]
could you guys kindly inform us what to do in order to make it work. 
As of now I have in my method 

`
`var provider = new DpapiDataProtectionProvider("MyWebProject");
UserManager.UserTokenProvider = new DataProtectorTokenProvider<ApplicationUser>(provider.Create("EmailConfirmation"));

string code = await UserManager.GenerateEmailConfirmationTokenAsync(newUser.Id);
var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = newUser.Id, code = code }, protocol: Request.Url.Scheme);

await UserManager.SendEmailAsync(newUser.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>. Password is: " + randomPass);`
`

When running the code, an email is never sent.
